/****************************************************
*Hello.Java
****************************************************
*Tyler Brightwell
*01/15/2020
*CMSC 255 003
***************************************************/
public class Hello {
	public static void main(String[] args) {
		System.out.println("<Tyler Brightwell>");
		System.out.println("<Hello.Java>");
		System.out.println("<Hello.World>");
		System.out.println("<01/15/2020>");
		System.out.println("<CMSC 255 003>");
		System.out.println();
		}
}
